"""created_at attr created in MonitoredAd model

Revision ID: 8be5866814a7
Revises: e15fdc073ddb
Create Date: 2024-02-01 12:37:59.041600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8be5866814a7'
down_revision = 'e15fdc073ddb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monitored_ad', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monitored_ad', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
