"""added two attrs webpage_tracking and page_content_hash in MonitoredAd

Revision ID: dcf31d42f047
Revises: e1fc26fc31ae
Create Date: 2024-02-11 07:29:08.032397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcf31d42f047'
down_revision = 'e1fc26fc31ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monitored_ad', schema=None) as batch_op:
        batch_op.add_column(sa.Column('page_content_hash', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monitored_ad', schema=None) as batch_op:
        batch_op.drop_column('page_content_hash')

    # ### end Alembic commands ###
