"""page_content_hash attr is added but the boolean attr webpage_tracking is removed from MonitoredAd

Revision ID: fa2f84e02bb6
Revises: dcf31d42f047
Create Date: 2024-02-11 11:14:47.661005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa2f84e02bb6'
down_revision = 'dcf31d42f047'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monitored_ad', schema=None) as batch_op:
        batch_op.drop_column('webpage_tracking')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monitored_ad', schema=None) as batch_op:
        batch_op.add_column(sa.Column('webpage_tracking', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
